name: vexana
description: Manage your network layer with dio. You will be able to use it very
  easily network operations.
author: Veli Bacik <vbacik.10@gmail.com>
version: 2.8.0
homepage: https://github.com/VB10/vexana

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0

  # Core
  dio: ^4.0.4
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logger: ^1.0.0

  # Database
  path_provider: ^2.0.1

  # Utiltiy
  retry: ^3.1.0
  sembast: ^3.0.0+4
  shared_preferences: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  mockito: ^5.0.0
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.0
